# Generated by Django 3.2.8 on 2021-10-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_address_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
