# Generated by Django 3.2.8 on 2021-10-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20211022_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
