# Generated by Django 3.2.8 on 2021-10-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_post_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Gender',
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('G.k and Learning', 'G.k and Learning'), ('Government Jobs', 'Government Jobs'), ('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Science and Arts', 'Science and Arts'), ('School Level', 'School Level'), ('International Exams', 'International Exams'), ('Finance', 'Finance'), ('Commerce', 'Commerce'), ('Dictionary', 'Dictionary'), ('Children Books', 'Children Books'), ('Fiction', 'Fiction'), ('Non Fiction', 'Non Fiction'), ('Motivation and Self Help', 'Motivation and Self Help'), ('Religion And Spirituality', 'Religion And Siprituality'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
