# Generated by Django 3.2.8 on 2021-11-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20211023_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmodel',
            name='has_unread',
        ),
    ]
